// Generated by maintenance/build.cjs. Edit maintenance/src, then rebuild.

// catalog-helpers.js
// Flat list used by search/preview/activity helpers.
const WebShelfSites = WebShelfCategories.flatMap((category) =>
  category.sites.map((site) => ({
    ...site,
    category: category.title,
    categoryKey: category.key,
    group: category.group || "Other"
  }))
);

function getSiteBadges(site) {
  return Array.isArray(site?.badges)
    ? site.badges.filter(Boolean).map(String)
    : [];
}

function siteHasBadge(site, badge) {
  const wanted = String(badge || "").trim().toLowerCase();
  return getSiteBadges(site).some(
    (value) => value.trim().toLowerCase() === wanted
  );
}

function getSiteDomain(site) {
  try {
    return new URL(site?.url || "").hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

function escapeWebShelfText(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function renderSiteBadges(site, options = {}) {
  const badges = getSiteBadges(site);
  const interactive = options.interactive !== false;

  if (badges.length === 0) return "";

  return `
    <span class="site-badges" aria-label="Site badges">
      ${badges.map((badge) => {
        const value = String(badge);
        const safeValue = escapeWebShelfText(value);
        const className = value.toLowerCase().replace(/[^a-z0-9]+/g, "-");
        const interactiveAttributes = interactive
          ? `data-badge-filter="${safeValue}" role="button" tabindex="0" title="Filter by ${safeValue}"`
          : `aria-label="${safeValue}"`;

        return `<span class="site-badge site-badge--${className}" ${interactiveAttributes}>${safeValue}</span>`;
      }).join("")}
    </span>
  `;
}

;

// runtime.js
// Shared data boundaries. No markup or layout changes.
(() => {
  const temporary = new Map();
  let warned = false;
  function warn() {
    if (!warned) console.warn('WebShelf: browser storage is unavailable. Changes in this page may not survive a reload.');
    warned = true;
  }
  const storage = {
    getItem(key) {
      if (temporary.has(key)) return temporary.get(key);
      try { return localStorage.getItem(key); } catch { warn(); return null; }
    },
    setItem(key, value) {
      const text = String(value);
      try { localStorage.setItem(key, text); temporary.delete(key); }
      catch { temporary.set(key, text); warn(); }
    },
    removeItem(key) {
      try { localStorage.removeItem(key); temporary.delete(key); }
      catch { temporary.set(key, null); warn(); }
    }
  };
  function safeUrl(value, relative = false) {
    if (typeof value !== 'string' || !value.trim() || /[\u0000-\u0020\u007f\\]/.test(value)) return '';
    try {
      const base = location.href.startsWith('file:') ? 'https://webshelf.invalid/' : location.href;
      const parsed = relative ? new URL(value, base) : new URL(value);
      if (!['https:', 'http:'].includes(parsed.protocol) || parsed.username || parsed.password) return '';
      return value;
    } catch { return ''; }
  }
  const catalog = new Map(WebShelfSites.map(site => [site.url, site]));
  const memo = new Map();
  function savedSites(key) {
    const raw = storage.getItem(key);
    const cached = memo.get(key);
    if (cached?.raw === raw) return cached.sites.map(site => ({...site}));
    let source;
    try { source = JSON.parse(raw || '[]'); } catch { source = []; }
    const seen = new Set();
    const sites = (Array.isArray(source) ? source : []).filter(site => {
      if (!site || typeof site !== 'object' || !safeUrl(site.url) || typeof site.name !== 'string' || !site.name.trim() || seen.has(site.url)) return false;
      seen.add(site.url); return true;
    }).map(site => {
      const current = catalog.get(site.url);
      // Retain history, but use current catalog metadata for known sites.
      return {...site, ...current, name: current?.name || site.name, icon: safeUrl(current?.icon || site.icon, true), badges: current?.badges || (Array.isArray(site.badges) ? site.badges.filter(b => typeof b === 'string') : [])};
    });
    memo.set(key, {raw, sites});
    return sites.map(site => ({...site}));
  }
  // Set inert without replacing nodes or changing visual styles.
  function modalBackground(overlay) {
    const saved = new Map();
    for (const node of document.body.children) {
      if (node === overlay || node.tagName === 'SCRIPT') continue;
      saved.set(node, node.inert); node.inert = true;
    }
    return () => { for (const [node, inert] of saved) node.inert = inert; };
  }
  function bindForm(form, status, button, messages) {
    if (!form || !status || !button) return;
    let pending = false;
    status.setAttribute('role', 'status');
    const fields = [...form.querySelectorAll('input[type="url"]')];
    const validate = () => {
      for (const field of fields) field.setCustomValidity(!field.value || safeUrl(field.value) ? '' : 'Enter a complete http:// or https:// website URL.');
    };
    for (const field of fields) field.addEventListener('input', validate);
    form.addEventListener('submit', async event => {
      event.preventDefault();
      if (pending) return;
      validate();
      if (!form.reportValidity()) return;
      pending = true;
      const original = button.textContent;
      const body = new FormData(form);
      const fingerprint = data => JSON.stringify([...data.entries()]);
      const submitted = fingerprint(body);
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 20000);
      form.setAttribute('aria-busy', 'true');
      status.textContent = messages.sending;
      button.disabled = true; button.textContent = 'Sending...';
      try {
        const response = await fetch(form.action, {method:'POST', body, headers:{Accept:'application/json'}, signal:controller.signal});
        status.textContent = response.ok ? messages.success : 'Something went wrong. Please try again.';
        if (response.ok && fingerprint(new FormData(form)) === submitted) form.reset();
      } catch {
        // Never retry a POST automatically: the server may already have received it.
        status.textContent = messages.failure;
      } finally {
        clearTimeout(timeout); pending = false;
        form.removeAttribute('aria-busy'); button.disabled = false; button.textContent = original;
      }
    });
  }
  window.WebShelfRuntime = {storage, safeUrl, savedSites, modalBackground, bindForm};
  window.addEventListener('storage', event => {
    if (event.storageArea && event.storageArea !== localStorage) return;
    if (event.key === null) { temporary.clear(); memo.clear(); }
    else { temporary.delete(event.key); memo.delete(event.key); }
    const names = {'webshelf-favorites':'webshelf-favorites-changed', 'webshelf-recently-viewed':'webshelf-activity-changed', 'webshelf-hidden-sites':'webshelf-hidden-changed', 'webshelf-theme':'webshelf-theme-changed'};
    for (const [key,name] of Object.entries(names)) if (event.key === null || event.key === key) document.dispatchEvent(new CustomEvent(name));
  });
})();

;

// icons.js
// ==================================================
// SMALL LOCAL ICON SET
// Replaces the external Lucide CDN for faster/offline-safe rendering.
// ==================================================

(() => {
  const icons = {
    play: '<polygon points="9 6 18 12 9 18 9 6"></polygon>',
    "book-open": '<path d="M4 5.5c2.8 0 5 .7 8 2.5v11c-3-1.8-5.2-2.5-8-2.5z"></path><path d="M20 5.5c-2.8 0-5 .7-8 2.5v11c3-1.8 5.2-2.5 8-2.5z"></path>',
    download: '<path d="M12 4v11"></path><path d="m8 11 4 4 4-4"></path><path d="M5 20h14"></path>',
    database: '<ellipse cx="12" cy="5" rx="7" ry="3"></ellipse><path d="M5 5v7c0 1.7 3.1 3 7 3s7-1.3 7-3V5"></path><path d="M5 12v7c0 1.7 3.1 3 7 3s7-1.3 7-3v-7"></path>',
    "calendar-days": '<rect x="4" y="5" width="16" height="15" rx="2"></rect><path d="M8 3v4M16 3v4M4 10h16"></path><path d="M8 14h2M14 14h2M8 17h2"></path>',
    folder: '<path d="M3 7.5a2 2 0 0 1 2-2h5l2 2h7a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>',
    "circle-alert": '<circle cx="12" cy="12" r="9"></circle><path d="M12 7v6M12 17h.01"></path>',
    "layers-3": '<path d="m12 3 8 4-8 4-8-4z"></path><path d="m4 12 8 4 8-4"></path><path d="m4 17 8 4 8-4"></path>'
  };

  function render(root = document) {
    root.querySelectorAll("[data-lucide]").forEach((element) => {
      if (element.dataset.iconRendered === "true") return;
      const name = element.getAttribute("data-lucide") || "folder";
      const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
      svg.setAttribute("viewBox", "0 0 24 24");
      svg.setAttribute("width", "24");
      svg.setAttribute("height", "24");
      svg.setAttribute("fill", "none");
      svg.setAttribute("stroke", "currentColor");
      svg.setAttribute("stroke-width", "1.8");
      svg.setAttribute("stroke-linecap", "round");
      svg.setAttribute("stroke-linejoin", "round");
      svg.setAttribute("aria-hidden", "true");
      svg.innerHTML = Object.hasOwn(icons, name) ? icons[name] : icons.folder;
      if (element.id) svg.id = element.id;
      element.replaceWith(svg);
      svg.dataset.iconRendered = "true";
    });
  }

  window.WebShelfIcons = { render };
  // Compatibility with existing calls while removing the external dependency.
  window.lucide = { createIcons: render };
})();

// Capture image errors before dynamically rendered logos start loading.
document.addEventListener('error', (event) => {
  const image = event.target;
  if (!(image instanceof HTMLImageElement)) return;
  if (!image.closest('.site-logo, .recently-logo, .search-result-logo, .activity-logo, .recent-change-logo, .logo')) return;
  const fallback = document.createElement('span');
  fallback.className = 'logo-fallback';
  fallback.textContent = (image.alt || 'W').replace(/ logo$/i, '').trim().slice(0, 1).toUpperCase() || 'W';
  fallback.setAttribute('aria-hidden', 'true');
  image.replaceWith(fallback);
}, true);

;

// hidden.js
// ==================================================
// PERSONAL HIDDEN / NOT INTERESTED SITES
// ==================================================

const HIDDEN_SITES_KEY = "webshelf-hidden-sites";

function getHiddenSites() {
  try {
    const saved = JSON.parse(WebShelfRuntime.storage.getItem(HIDDEN_SITES_KEY) || "[]");
    return Array.isArray(saved) ? [...new Set(saved.filter(url => WebShelfRuntime.safeUrl(url)))] : [];
  } catch {
    return [];
  }
}

function saveHiddenSites(urls) {
  WebShelfRuntime.storage.setItem(
    HIDDEN_SITES_KEY,
    JSON.stringify([...new Set(urls.filter(Boolean))])
  );
}

function isSiteHidden(url) {
  return getHiddenSites().includes(url);
}

function updateHiddenUI() {
  const count = getHiddenSites().length;

  document.querySelectorAll("[data-hidden-count]").forEach((element) => {
    element.textContent = String(count);
  });

  document.querySelectorAll(".hidden-sites-link").forEach((element) => {
    element.hidden = count === 0;
  });

  const hiddenTab = document.querySelector("#hidden-sites-tab");
  if (hiddenTab) hiddenTab.hidden = count === 0;

  if (count === 0 && location.hash === "#hidden") {
    history.replaceState(null, "", location.pathname + location.search);
  }
}

function setSiteHidden(url, hidden = true) {
  if (!WebShelfRuntime.safeUrl(url)) return;
  const urls = getHiddenSites();
  const next = hidden
    ? [...urls, url]
    : urls.filter((item) => item !== url);

  saveHiddenSites(next);
  updateHiddenUI();

  document.dispatchEvent(
    new CustomEvent("webshelf-hidden-changed", {
      detail: { url, hidden }
    })
  );
}

function toggleSiteHidden(url) {
  const hidden = !isSiteHidden(url);
  setSiteHidden(url, hidden);
  return hidden;
}

function filterVisibleSites(sites) {
  const hidden = new Set(getHiddenSites());
  return (Array.isArray(sites) ? sites : []).filter(site => !hidden.has(site.url));
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", updateHiddenUI);
} else {
  updateHiddenUI();
}

document.addEventListener("webshelf-hidden-changed", updateHiddenUI);

;

// history-store.js
// Bounded history: retain up to 250 sites, 30 calendar days of counts, and 512 KiB.
const RECENTLY_VIEWED_KEY = 'webshelf-recently-viewed';
const HISTORY_MAX_SITES = 250;
const HISTORY_MAX_BYTES = 512 * 1024;
const HISTORY_DAYS = 30;
const HISTORY_DAY_MS = 86400000;
function historyDay(time) {
  const date = new Date(time);
  return Math.floor(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()) / HISTORY_DAY_MS);
}
function normalizeActivitySite(site) {
  const now = Date.now(), today = historyDay(now), days = new Map();
  const add = (day, count) => {
    if (Number.isInteger(day) && day > today - HISTORY_DAYS && day <= today && Number.isSafeInteger(count) && count > 0) {
      days.set(day, Math.min(Number.MAX_SAFE_INTEGER, (days.get(day) || 0) + count));
    }
  };
  if (Array.isArray(site.visitDays)) {
    for (const item of site.visitDays) if (item) add(item.day, item.count);
  } else if (Array.isArray(site.visitTimestamps)) {
    for (const time of site.visitTimestamps) if (Number.isFinite(time) && time > 0 && time <= now) add(historyDay(time), 1);
  } else if (Number.isFinite(site.lastVisited) && site.lastVisited > 0 && site.lastVisited <= now) {
    add(historyDay(site.lastVisited), 1);
  }
  const {visitTimestamps, ...rest} = site;
  return {...rest,
    visits: Number.isSafeInteger(site.visits) && site.visits >= 0 ? site.visits : Math.max(1, [...days.values()].reduce((a,b)=>a+b,0)),
    lastVisited: Number.isFinite(site.lastVisited) && site.lastVisited > 0 ? Math.min(site.lastVisited, now) : 0,
    visitDays: [...days].sort((a,b)=>a[0]-b[0]).map(([day,count])=>({day,count}))
  };
}
function compactHistory(sites) {
  const records = sites.map(normalizeActivitySite).sort((a,b)=>b.lastVisited-a.lastVisited).slice(0,HISTORY_MAX_SITES).map(site=>({
    name:site.name, url:site.url, icon:site.icon || '', visits:site.visits, lastVisited:site.lastVisited, visitDays:site.visitDays
  }));
  const bounded=[];let bytes=4;
  for(const record of records){
    const size=JSON.stringify(record).length*2+(bounded.length?2:0);
    if(bytes+size>HISTORY_MAX_BYTES)break;
    bytes+=size;bounded.push(record);
  }
  return bounded;
}
function saveRecentlyViewed(sites) {
  WebShelfRuntime.storage.setItem(RECENTLY_VIEWED_KEY, JSON.stringify(compactHistory(sites)));
}
function getRecentlyViewed() {
  const sites=WebShelfRuntime.savedSites(RECENTLY_VIEWED_KEY);
  const compact=compactHistory(sites), serialized=JSON.stringify(compact);
  if (serialized !== WebShelfRuntime.storage.getItem(RECENTLY_VIEWED_KEY)) WebShelfRuntime.storage.setItem(RECENTLY_VIEWED_KEY, serialized);
  const known=new Map(sites.map(site=>[site.url,site]));
  return compact.map(site=>({...known.get(site.url),...site}));
}
function addRecentlyViewed(site) {
  if (!site || !WebShelfRuntime.safeUrl(site.url)) return;
  const sites=getRecentlyViewed(),existing=sites.find(item=>item.url===site.url),now=Date.now(),day=historyDay(now);
  const visitDays=(existing?.visitDays || []).map(item=>({...item})),bucket=visitDays.find(item=>item.day===day);
  if(bucket)bucket.count=Math.min(Number.MAX_SAFE_INTEGER,bucket.count+1);else visitDays.push({day,count:1});
  const updated={...existing,...site,visits:existing?Math.min(Number.MAX_SAFE_INTEGER,existing.visits+1):1,lastVisited:now,visitDays};
  saveRecentlyViewed([updated,...sites.filter(item=>item.url!==site.url)]);
  document.dispatchEvent(new CustomEvent('webshelf-activity-changed'));
}

document.addEventListener("click", (event) => {
  const link = event.target.closest(".site-link");
  if (!link) return;
  const row = link.closest(".site-row");
  if (!row) return;

  const site = typeof WebShelfSites !== "undefined"
    ? WebShelfSites.find((item) => item.url === link.href || item.url === link.getAttribute("href"))
    : null;

  if (site) {
    addRecentlyViewed(site);
    return;
  }

  const name = row.querySelector(".site-name")?.textContent.trim();
  const image = row.querySelector(".site-logo img");
  if (name) addRecentlyViewed({ name, url: link.href, icon: image?.getAttribute("src") || "" });
});

;

// navigation.js
// ==================================================
// WEBSHELF NAVIGATION
// ==================================================

(() => {

  const navLinks =
    document.querySelector(
      ".nav-links"
    );

  const header =
    document.querySelector(
      ".site-header"
    );

  if (!navLinks || !header) {
    return;
  }

  const currentFile =
    window.location.pathname
      .split("/")
      .pop() ||
    "index.html";

  const activeClass =
    currentFile === "activity.html"
      ? "activity"
      : currentFile === "support.html"
        ? "support"
        : currentFile === "suggest.html"
          ? "suggest"
          : "directory";

  navLinks
    .querySelectorAll("a")
    .forEach((link) => {
      if (link.classList.contains(activeClass)) link.setAttribute("aria-current", "page");
      else link.removeAttribute("aria-current");
      link.classList.toggle(
        "active",
        link.classList.contains(
          activeClass
        )
      );
    });

  const menuToggle =
    document.createElement(
      "button"
    );

  menuToggle.className =
    "nav-menu-toggle";
  menuToggle.type = "button";
  menuToggle.setAttribute(
    "aria-label",
    "Open navigation menu"
  );
  menuToggle.setAttribute(
    "aria-expanded",
    "false"
  );
  menuToggle.textContent = "☰";

  navLinks.appendChild(
    menuToggle
  );

  const mobileMenu =
    document.createElement(
      "div"
    );

  mobileMenu.id = "webshelf-mobile-menu";
  menuToggle.setAttribute("aria-controls", mobileMenu.id);
  mobileMenu.className =
    "mobile-nav-menu";
  mobileMenu.hidden = true;

  navLinks
    .querySelectorAll(
      ":scope > a"
    )
    .forEach((link) => {

      const clone =
        link.cloneNode(true);

      mobileMenu.appendChild(
        clone
      );

    });

  header.appendChild(
    mobileMenu
  );

  function open() {
    mobileMenu.hidden = false;
    menuToggle.setAttribute("aria-label", "Close navigation menu");
    mobileMenu.classList.add("open");
    menuToggle.classList.add("active");
    menuToggle.setAttribute(
      "aria-expanded",
      "true"
    );
  }

  function close() {
    if (mobileMenu.contains(document.activeElement)) menuToggle.focus();
    menuToggle.setAttribute("aria-label", "Open navigation menu");
    mobileMenu.hidden = true;
    mobileMenu.classList.remove("open");
    menuToggle.classList.remove("active");
    menuToggle.setAttribute(
      "aria-expanded",
      "false"
    );
  }

  function isOpen() {
    return !mobileMenu.hidden;
  }

  menuToggle.addEventListener(
    "click",
    () => {
      isOpen()
        ? close()
        : open();
    }
  );

  document.addEventListener(
    "click",
    (event) => {

      if (!isOpen()) {
        return;
      }

      if (
        header.contains(
          event.target
        )
      ) {
        return;
      }

      close();

    }
  );

  window.addEventListener(
    "resize",
    () => {
      if (window.innerWidth > 700) {
        close();
      }
    }
  );

  window.WebShelfNavigation = {
    open,
    close,
    isOpen
  };

})();

;

// shortcuts.js
// ==================================================
// KEYBOARD SHORTCUTS
// ==================================================

(() => {
  function isTypingTarget(target) {
    return (
      target instanceof HTMLElement &&
      (target.matches("input, textarea, select") || target.isContentEditable)
    );
  }

  document.addEventListener("keydown", (event) => {
    if (event.defaultPrevented || event.isComposing) return;
    const typing = isTypingTarget(event.target);

    if (event.key === "Escape") {
      window.WebShelfPreview?.close?.();
      window.WebShelfSearch?.close?.();
      window.WebShelfNavigation?.close?.();
      window.WebShelfDialog?.close?.();
      return;
    }

    const searchKey =
      !typing &&
      !document.querySelector(".webshelf-dialog-overlay:not([hidden])") &&
      !event.ctrlKey &&
      !event.metaKey &&
      !event.altKey &&
      event.key.toLowerCase() === "f";

    if (searchKey) {
      event.preventDefault();
      window.WebShelfSearch?.open?.();
    }
  });
})();

;

// theme.js
// ==================================================
// THEME
// ==================================================

const themeToggle =
  document.querySelector("#theme-toggle");


const savedTheme =
  WebShelfRuntime.storage.getItem("webshelf-theme");


if (savedTheme === "dark" || savedTheme === "light") {

  document.documentElement.setAttribute(
    "data-theme",
    savedTheme
  );

}


function updateThemeButton() {
  const themeColor = document.querySelector('meta[name="theme-color"]');
  if (themeColor) themeColor.setAttribute("content", document.documentElement.getAttribute("data-theme") === "light" ? "#f5f5f7" : "#000000");

  if (!themeToggle) {
    return;
  }


  const currentTheme =
    document.documentElement.getAttribute(
      "data-theme"
    );


  if (currentTheme === "light") {

    themeToggle.textContent = "☾";

    themeToggle.setAttribute(
      "aria-label",
      "Switch to dark mode"
    );

  } else {

    themeToggle.textContent = "☀";

    themeToggle.setAttribute(
      "aria-label",
      "Switch to light mode"
    );

  }

}


if (themeToggle) {

  updateThemeButton();


  themeToggle.addEventListener(
    "click",
    () => {

      const currentTheme =
        document.documentElement.getAttribute(
          "data-theme"
        );


      const newTheme =
        currentTheme === "light"
          ? "dark"
          : "light";


      document.documentElement.setAttribute(
        "data-theme",
        newTheme
      );


      WebShelfRuntime.storage.setItem(
        "webshelf-theme",
        newTheme
      );


      updateThemeButton();

    }
  );

}
document.addEventListener("webshelf-theme-changed", () => {
  const theme = WebShelfRuntime.storage.getItem("webshelf-theme");
  document.documentElement.setAttribute("data-theme", theme === "light" ? "light" : "dark");
  updateThemeButton();
});

;

// pwa.js
// ==================================================
// PWA / INSTALL WEBSHELF
// ==================================================

(() => {
  if ("serviceWorker" in navigator && location.protocol !== "file:") {
    window.addEventListener("load", () => {
      navigator.serviceWorker.register("./service-worker.js").catch(() => {});
    });
  }

  let installPrompt = null;
  const buttons = [];

  function createButton(className = "install-app-button") {
    const button = document.createElement("button");
    button.className = className;
    button.type = "button";
    button.hidden = true;
    button.textContent = "Install app";
    button.setAttribute("aria-label", "Install WebShelf app");
    button.addEventListener("click", async () => {
      if (!installPrompt) return;
      const prompt = installPrompt;
      installPrompt = null;
      buttons.forEach((item) => { item.hidden = true; });
      try {
        await prompt.prompt();
        await prompt.userChoice;
      } catch { /* A dismissed or expired prompt must not reject globally. */ }
    });
    buttons.push(button);
    return button;
  }

  const footerLinks = document.querySelector(".footer-links");
  if (footerLinks) {
    footerLinks.appendChild(createButton("install-app-button footer-install-button"));
  }

  const mobileMenu = document.querySelector(".mobile-nav-menu");
  if (mobileMenu) {
    mobileMenu.appendChild(createButton("install-app-button mobile-install-button"));
  }

  window.addEventListener("beforeinstallprompt", (event) => {
    event.preventDefault();
    installPrompt = event;
    buttons.forEach((button) => { button.hidden = false; });
  });

  window.addEventListener("appinstalled", () => {
    installPrompt = null;
    buttons.forEach((button) => { button.hidden = true; });
  });
})();

;

// search.js
// ==================================================
// WEBSHELF SEARCH
// ==================================================

(() => {
  const SEARCH_RESULT_LIMIT = 60;

  const safeText = (value) => typeof escapeWebShelfText === "function"
    ? escapeWebShelfText(value)
    : String(value ?? "");

  const getSearchSites = () => {
    const source = Array.isArray(WebShelfSites) ? WebShelfSites : [];
    return typeof filterVisibleSites === "function" ? filterVisibleSites(source) : source;
  };

  const overlay = document.createElement("div");
  overlay.className = "search-overlay";
  overlay.hidden = true;
  overlay.innerHTML = `
    <div class="search-modal" role="dialog" aria-modal="true" aria-label="Search WebShelf">
      <div class="search-header">
        <div class="search-input-wrapper">
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <circle cx="11" cy="11" r="7"></circle>
            <path d="M20 20L16.5 16.5"></path>
          </svg>
          <input
            class="search-input"
            id="webshelf-search-title"
            aria-label="Search websites" role="combobox" aria-autocomplete="list" aria-expanded="true" aria-controls="webshelf-search-results"
            type="search"
            placeholder="Search websites, categories..."
            autocomplete="off"
            spellcheck="false"
          >
        </div>
        <button class="search-close" type="button" aria-label="Close search">×</button>
      </div>
      <div class="search-toolbar">
        <div class="search-info" aria-live="polite"></div>
        <label class="search-category-label">
          <span class="sr-only">Filter search by category</span>
          <select class="search-category-filter" aria-label="Filter search by category">
            <option value="all">All categories</option>
          </select>
        </label>
      </div>
      <div class="search-results" id="webshelf-search-results" role="listbox" aria-label="Search results"></div>
    </div>`;
  document.body.appendChild(overlay);

  const modal = overlay.querySelector(".search-modal");
  const input = overlay.querySelector(".search-input");
  const results = overlay.querySelector(".search-results");
  const info = overlay.querySelector(".search-info");
  const categoryFilter = overlay.querySelector(".search-category-filter");
  const closeButton = overlay.querySelector(".search-close");
  const heroSearch = document.querySelector("#hero-search-trigger");
  const heroSearchCount = document.querySelector("#hero-search-count");

  let previousFocus = null;
  let restoreBackground = null;
  const searchIndex = new WeakMap();
  let activeResultIndex = -1;
  let currentMatches = [];

  if (Array.isArray(WebShelfCategories)) {
    categoryFilter.insertAdjacentHTML(
      "beforeend",
      WebShelfCategories.map((category) => `<option value="${safeText(category.key)}">${safeText(category.title)}</option>`).join("")
    );
  }

  if (heroSearchCount) {
    heroSearchCount.textContent = `${getSearchSites().length} websites`;
  }

    function normalizeQuery(value) {
      const raw = String(value || "").trim().toLowerCase();
      if (!raw) return "";

      // Partial Arabic search:
      // ara / arab / arabi / arabic → AR badge
      if (raw.length >= 3 && "arabic".startsWith(raw)) {
        return "ar";
      }

        const aliases = new Map([
          ["arabic subtitles", "ar"],
          ["arabic subtitle", "ar"],

          ["عر", "ar"],
          ["عرب", "ar"],
          ["عربي", "ar"],
          ["العربي", "ar"],
          ["العربية", "ar"]
        ]);

      return aliases.get(raw) || raw;
    }

  function siteSearchText(site) {
    return {
      name: String(site.name || "").toLowerCase(),
      domain: typeof getSiteDomain === "function" ? getSiteDomain(site).toLowerCase() : "",
      category: String(site.category || "").toLowerCase(),
      group: String(site.group || "").toLowerCase(),
      description: String(site.description || "").toLowerCase(),
      badges: getSiteBadges(site).join(" ").toLowerCase()
    };
  }

  function scoreSite(site, query) {
    if (!searchIndex.has(site)) searchIndex.set(site, siteSearchText(site));
    const text = searchIndex.get(site);
    let score = 0;
    if (text.name === query) score += 120;
    else if (text.name.startsWith(query)) score += 90;
    else if (text.name.includes(query)) score += 70;

    if (text.domain === query) score += 85;
    else if (text.domain.startsWith(query)) score += 65;
    else if (text.domain.includes(query)) score += 50;

    if (text.category.includes(query)) score += 40;
    if (text.badges.split(/\s+/).includes(query)) score += 45;
    else if (text.badges.includes(query)) score += 30;
    if (text.description.includes(query)) score += 25;
    if (text.group.includes(query)) score += 18;
    return score;
  }

  function filteredAndRankedSites() {
    const query = normalizeQuery(input.value);
    const selectedCategory = categoryFilter.value;
    const candidates = getSearchSites().filter((site) => selectedCategory === "all" || site.categoryKey === selectedCategory);

    if (!query) return [];

    return candidates
      .map((site) => ({ site, score: scoreSite(site, query) }))
      .filter((item) => item.score > 0)
      .sort((a, b) => b.score - a.score || String(a.site.name).localeCompare(String(b.site.name)))
      .map((item) => item.site);
  }

  function setActiveResult(index, scroll = true) {
    if (index === activeResultIndex) return;
    const items = [...results.querySelectorAll(".search-result")];
    if (!items.length) {
      activeResultIndex = -1;
      return;
    }

    input.setAttribute("aria-activedescendant", "webshelf-result-" + Math.max(0, Math.min(index, items.length - 1)));
    activeResultIndex = Math.max(0, Math.min(index, items.length - 1));
    items.forEach((item, itemIndex) => {
      const active = itemIndex === activeResultIndex;
      item.classList.toggle("active", active);
      item.setAttribute("aria-selected", String(active));
      if (active && scroll) item.scrollIntoView({ block: "nearest" });
    });
  }

  function renderResults(matches) {
    const sites = getSearchSites();
    const query = input.value.trim();
    input.removeAttribute("aria-activedescendant");
    currentMatches = matches;
    activeResultIndex = -1;

    if (!query) {
      const filteredCount = categoryFilter.value === "all"
        ? sites.length
        : sites.filter((site) => site.categoryKey === categoryFilter.value).length;
      info.textContent = `Search ${filteredCount} websites`;
      results.innerHTML = `<div class="search-empty">Start typing to search WebShelf.</div>`;
      return;
    }

    const visible = matches.slice(0, SEARCH_RESULT_LIMIT);
    info.textContent = matches.length > SEARCH_RESULT_LIMIT
      ? `${matches.length} results · showing first ${SEARCH_RESULT_LIMIT}`
      : `${matches.length} ${matches.length === 1 ? "result" : "results"}`;

    if (!matches.length) {
      results.innerHTML = `<div class="search-empty">No websites found.</div>`;
      return;
    }

    results.innerHTML = visible.map((site, index) => {
      const name = safeText(site.name);
      const logo = site.icon
        ? `<img src="${safeText(site.icon)}" loading="lazy" decoding="async" alt="${name} logo">`
        : `<span>${name.charAt(0)}</span>`;
      const description = String(site.description || "").trim();
      const domain = typeof getSiteDomain === "function" ? getSiteDomain(site) : "";
      const secondary = description || [domain, site.category].filter(Boolean).join(" · ");

      return `
        <a class="search-result" id="webshelf-result-${index}" role="option" aria-selected="false" data-search-index="${index}" href="${safeText(site.url)}" target="_blank" rel="noopener noreferrer" data-site-url="${safeText(site.url)}">
          <div class="search-result-logo">${logo}</div>
          <div class="search-result-text">
            <span class="search-result-name-line"><span class="search-result-name">${name}</span>${renderSiteBadges(site, { interactive: false })}</span>
            <span class="search-result-category">${safeText(secondary)}</span>
          </div>
          <span class="search-result-arrow">↗</span>
        </a>`;
    }).join("");
  }

  function searchWebShelf() {
    renderResults(filteredAndRankedSites());
  }

  function open(initialQuery = "") {
    if (isOpen()) { input.focus(); return; }
    window.WebShelfNavigation?.close?.();
    window.WebShelfPreview?.close?.();
    previousFocus = document.activeElement;
    overlay.hidden = false;
    restoreBackground = WebShelfRuntime.modalBackground(overlay);
    document.body.classList.add("search-open");
    input.value = initialQuery;
    categoryFilter.value = "all";
    searchWebShelf();
    requestAnimationFrame(() => { if (isOpen()) input.focus(); });
  }

  function close() {
    if (overlay.hidden) return;
    overlay.hidden = true;
    restoreBackground?.(); restoreBackground = null;
    document.body.classList.remove("search-open");
    activeResultIndex = -1;
    const target = previousFocus;
    previousFocus = null;
    if (target && typeof target.focus === "function" && document.contains(target)) {
      target.focus();
    }
  }

  function isOpen() {
    return !overlay.hidden;
  }

  function trapFocus(event) {
    if (event.key !== "Tab" || !isOpen()) return;
    const focusable = [...modal.querySelectorAll('button:not([disabled]), input:not([disabled]), select:not([disabled]), a[href]')]
      .filter((element) => element.offsetParent !== null);
    if (!focusable.length) return;

    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  }

  heroSearch?.addEventListener("click", () => open());
  closeButton.addEventListener("click", close);
  input.addEventListener("input", searchWebShelf);
  categoryFilter.addEventListener("change", searchWebShelf);

  input.addEventListener("keydown", (event) => {
    if (event.isComposing) return;
    const visibleCount = Math.min(currentMatches.length, SEARCH_RESULT_LIMIT);
    if (event.key === "ArrowDown" && visibleCount) {
      event.preventDefault();
      setActiveResult(activeResultIndex < 0 ? 0 : (activeResultIndex + 1) % visibleCount);
    } else if (event.key === "ArrowUp" && visibleCount) {
      event.preventDefault();
      setActiveResult(activeResultIndex < 0 ? visibleCount - 1 : (activeResultIndex - 1 + visibleCount) % visibleCount);
    } else if (event.key === "Enter" && activeResultIndex >= 0) {
      event.preventDefault();
      results.querySelector(`.search-result[data-search-index="${activeResultIndex}"]`)?.click();
    }
  });

  overlay.addEventListener("click", (event) => {
    if (event.target === overlay) close();
  });

  results.addEventListener("mousemove", (event) => {
    const result = event.target.closest(".search-result");
    if (!result) return;
    const index = Number(result.dataset.searchIndex);
    if (Number.isFinite(index)) setActiveResult(index, false);
  });

  results.addEventListener("click", (event) => {
    const result = event.target.closest(".search-result");
    if (!result) return;
    const site = WebShelfSites.find((item) => item.url === result.dataset.siteUrl);
    if (site && typeof addRecentlyViewed === "function") addRecentlyViewed(site);
    close();
  });

  document.addEventListener("keydown", (event) => {
    trapFocus(event);
    if (event.key === "Escape" && isOpen()) {
      event.preventDefault();
      close();
    }
  });

  document.addEventListener("webshelf-hidden-changed", () => {
    if (heroSearchCount) heroSearchCount.textContent = `${getSearchSites().length} websites`;
    if (isOpen()) searchWebShelf();
  });

  renderResults([]);
  window.WebShelfSearch = { open, close, isOpen };
})();

;
