#!/usr/bin/env node
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const L=require('./lib.cjs');
function outputs(root=L.ROOT,catalog=L.readCatalog(root)){
 const errors=L.checkCatalog(catalog);if(errors.length)throw Error(errors.join('\n'));
 const out={'data.js':L.generateData(catalog)};
 for(const [page,parts]of Object.entries(L.pages)){
  const name=L.fileFor(page);
  const code='// Generated by maintenance/build.cjs. Edit maintenance/src, then rebuild.\n'+parts.map(file=>'\n// '+file+'.js\n'+fs.readFileSync(path.join(root,'maintenance/src',file+'.js'),'utf8').replace(/\r\n/g,'\n')+'\n;\n').join('')+(page==='common'?'':'\nwindow.lucide?.createIcons?.();\n');
  new vm.Script(code,{filename:name});out[name]=code;
 }
 // Keep sitemap bytes/dates untouched when internal category URLs have not changed.
 const sitemap=fs.readFileSync(path.join(root,'sitemap.xml'),'utf8');
 const matches=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]);
 const expected=catalog.map(c=>'https://www.webshelf.link/category.html?type='+encodeURIComponent(c.key));
 const current=matches.filter(u=>u.includes('/category.html?'));
 if(JSON.stringify([...current].sort())!==JSON.stringify([...expected].sort())){
  const urls=['https://www.webshelf.link/',...expected,'https://www.webshelf.link/suggest.html','https://www.webshelf.link/support.html'];
  out['sitemap.xml']='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>'  <url><loc>'+u.replaceAll('&','&amp;')+'</loc></url>').join('\n')+'\n</urlset>\n';
 }
 const template=fs.readFileSync(path.join(root,'maintenance/service-worker.source.js'),'utf8');
 const core=JSON.parse(fs.readFileSync(path.join(root,'maintenance/core.json'),'utf8'));
 const crypto=require('node:crypto'),hash=crypto.createHash('sha256');hash.update(template);
 for(const asset of core.filter(a=>a!=='./'))hash.update(out[asset.replace(/^\.\//,'')]??fs.readFileSync(path.join(root,asset)));
 // Icon changes also rotate the deployment cache, preserving the current strategy.
 for(const icon of [...new Set(L.flatten(catalog).map(x=>x.site.icon).filter(Boolean))].sort())hash.update(fs.readFileSync(path.join(root,icon)));
 out['service-worker.js']=template.replace('__VERSION__',hash.digest('hex').slice(0,12)).replace('__CORE__',JSON.stringify(core,null,2));
 for(const [file,text]of Object.entries(out))if(file.endsWith('.js'))new vm.Script(text,{filename:file});
 return out;
}
function build(root=L.ROOT){const generated=outputs(root),previous=new Map();try{for(const [file,text]of Object.entries(generated)){const p=path.join(root,file);previous.set(p,fs.existsSync(p)?fs.readFileSync(p):null);if(!previous.get(p)?.equals(Buffer.from(text)))L.atomic(p,text);}}catch(e){for(const[p,bytes]of previous)if(bytes)L.atomic(p,bytes);else if(fs.existsSync(p))fs.unlinkSync(p);throw e;}return Object.keys(generated);}
if(require.main===module){try{const files=build();console.log('Build passed: '+files.join(', '));}catch(e){console.error('Build failed: '+e.message);process.exitCode=1;}}
module.exports={outputs,build};
