const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'..');
const pages={common:['catalog-helpers','runtime','icons','hidden','history-store','navigation','shortcuts','theme','pwa','search'],index:['dialogs','favorites','history-ui','script','preview','badge-filters'],activity:['dialogs','activity','preview','badge-filters'],category:['dialogs','favorites','category','preview','badge-filters'],collection:['dialogs','favorites','collection','preview','badge-filters'],suggest:['suggest'],support:['support']};
const fileFor=p=>p==='common'?'common.js':p+'.bundle.js';
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
function atomic(file,bytes){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.'+crypto.randomUUID()+'.tmp';try{fs.writeFileSync(tmp,bytes,{flag:'wx'});fs.renameSync(tmp,file);}finally{if(fs.existsSync(tmp))fs.unlinkSync(tmp);}}
function readCatalog(root=ROOT){return JSON.parse(fs.readFileSync(path.join(root,'maintenance/catalog.json'),'utf8'));}
function normalizeURL(value){
 if(typeof value!=='string'||!value.trim()||/[\u0000-\u0020\u007f\\]/.test(value.trim()))throw Error('Invalid URL: use an HTTP(S) address without spaces or backslashes.');
 let s=value.trim();if(!/^[a-z][a-z\d+.-]*:/i.test(s)||/^[^\/:?#]+\.[a-z\d-]+:\d+(?:[/?#]|$)/i.test(s))s='https://'+s;
 let u;try{u=new URL(s);}catch{throw Error('Invalid URL: '+value);}
 if(!['http:','https:'].includes(u.protocol)||u.username||u.password||!u.hostname||(!u.hostname.includes('.')&&u.hostname!=='localhost'&&!u.hostname.includes(':')))throw Error('Invalid HTTP(S) URL: '+value);
 return u.href;
}
function urlKey(value){const u=new URL(normalizeURL(value));u.hash='';u.pathname=u.pathname.replace(/\/+$/,'')||'/';u.searchParams.sort();return u.href;}
const nameKey=s=>s.normalize('NFKC').trim().replace(/\s+/g,' ').toLocaleLowerCase('en');
function flatten(catalog){return catalog.flatMap((c,ci)=>c.sites.map((site,si)=>({site,category:c,ci,si})));}
function checkCatalog(catalog){
 const errors=[],urls=new Map(),names=new Map(),keys=new Set();if(!Array.isArray(catalog)||!catalog.length)return ['Catalog must be a non-empty array.'];
 for(const c of catalog){
  if(!c||typeof c!=='object'||typeof c.key!=='string'||!/^[A-Za-z0-9-]+$/.test(c.key)||keys.has(c.key)){errors.push('Invalid or duplicate category key: '+c?.key);continue;}keys.add(c.key);
  for(const field of ['title','group','icon','accent'])if(typeof c[field]!=='string'||!c[field].trim())errors.push(c.key+': missing '+field);
  if(!Array.isArray(c.sites)){errors.push(c.key+': sites must be an array');continue;}
  for(const s of c.sites){
   if(!s||typeof s!=='object'||typeof s.name!=='string'||!s.name.trim()||s.name.length>200){errors.push(c.key+': invalid site name');continue;}
   const label=s.name+' ['+c.key+']';
   try{const k=urlKey(s.url);if(urls.has(k))errors.push('Duplicate URL: '+label+' conflicts with '+urls.get(k));else urls.set(k,label);}catch(e){errors.push(label+': '+e.message);}
   const n=c.key+':'+nameKey(s.name);if(names.has(n))errors.push('Duplicate name in category: '+label+' conflicts with '+names.get(n));else names.set(n,label);
   for(const field of ['description','icon'])if(s[field]!==undefined&&typeof s[field]!=='string')errors.push(label+': '+field+' must be text');
   if(typeof s.icon==='string'&&s.icon&&!/^\.\/images\/icons\/[^/\\?#]+$/.test(s.icon))errors.push(label+': icons must use ./images/icons/ with exact casing');
   if(s.badges!==undefined&&(!Array.isArray(s.badges)||s.badges.some(b=>typeof b!=='string'||!b.trim())))errors.push(label+': badges must be nonempty strings');
   if(s.category!==undefined&&s.category!==c.key)errors.push(label+': invalid category reference');
  }
 }
 return errors;
}
function checksum(c){let h=2166136261;for(const ch of JSON.stringify(c).split(''))h=Math.imul(h^ch.charCodeAt(0),16777619);return(h>>>0).toString(16).padStart(8,'0');}
function generateData(c){return '// Generated by maintenance/build.cjs from maintenance/catalog.json. Do not edit by hand.\n// Catalog checksum: '+checksum(c)+'\nconst WebShelfCategories = '+JSON.stringify(c,null,2)+';\n';}
function walk(dir,rel=''){return fs.readdirSync(path.join(dir,rel),{withFileTypes:true}).flatMap(e=>{const p=rel?rel+'/'+e.name:e.name;return e.isDirectory()?walk(dir,p):[p];});}
function exactPath(root,rel){let dir=root;for(const part of rel.replaceAll('\\','/').split('/').filter(p=>p&&p!=='.')){if(part==='..'||!fs.existsSync(dir)||!fs.statSync(dir).isDirectory()||!fs.readdirSync(dir).includes(part))return false;dir=path.join(dir,part);}return fs.existsSync(dir);}
function publicFiles(root){return fs.readdirSync(root,{withFileTypes:true}).flatMap(e=>e.name==='images'?walk(root,'images'):e.isFile()&&!e.name.startsWith('.')&&e.name!=='README.md'?[e.name]:[]);}
module.exports={ROOT,pages,fileFor,digest,atomic,readCatalog,normalizeURL,urlKey,nameKey,flatten,checkCatalog,checksum,generateData,walk,exactPath,publicFiles};
