const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const L=require('../lib.cjs');
const H=require('../html-checks.cjs');
const SEO=require('../seo.cjs');
const read=f=>fs.readFileSync(path.join(L.ROOT,f),'utf8');
const config=JSON.parse(read('vercel.json'));
const catalog=L.readCatalog();
function text(n){return n.value || (n.childNodes||[]).map(text).join('');}
for(const cat of catalog) test('static SEO and Vercel mapping: '+cat.key,()=>{
  const html=read(SEO.fileFor(cat.key)), nodes=H.elements(html);
  const byId=id=>nodes.find(n=>H.attributes(n).id===id);
  const canon=nodes.filter(n=>H.attributes(n).rel==='canonical');
  assert.equal(canon.length,1);
  assert.equal(H.attributes(canon[0]).href,SEO.urlFor(cat.key));
  assert.equal(nodes.filter(n=>n.tagName==='h1').length,1);
  assert.equal(text(byId('category-page-title')),cat.title+' Sites');
  assert.ok(text(byId('category-page-description')).length>40);
  const anchors=nodes.filter(n=>n.tagName==='a').map(H.attributes);
  for(const site of cat.sites) assert.ok(anchors.some(a=>a.href===site.url),site.name);
  assert.equal(nodes.filter(n=>H.attributes(n).class==='site-row').length,cat.sites.length);
  const data=nodes.filter(n=>H.attributes(n).type==='application/ld+json').map(n=>JSON.parse(text(n)));
  assert.equal(data.length,1);
  assert.equal(data[0]['@graph'].find(n=>n['@type']==='ItemList').numberOfItems,cat.sites.length);
  assert.equal(H.attributes(nodes.find(n=>n.tagName==='body'))['data-category'],cat.key);
  const rule=config.rewrites.find(r=>r.has?.some(h=>h.value===cat.key));
  assert.equal(rule.source,'/category.html');
  assert.equal(rule.destination,'/'+SEO.fileFor(cat.key));
  assert.ok(L.publicFiles(L.ROOT).includes(SEO.fileFor(cat.key)));
  assert.deepEqual(H.checkScripts(html,SEO.fileFor(cat.key)),[]);
});
test('home contains all category links and useful listings without JavaScript',()=>{
  const nodes=H.elements(read('index.html'));
  const links=nodes.filter(n=>n.tagName==='a').map(H.attributes);
  for(const cat of catalog) assert.ok(links.some(a=>a.href==='./category.html?type='+cat.key));
  assert.equal(nodes.filter(n=>H.attributes(n).class==='site-row').length,60);
  assert.match(text(nodes.find(n=>n.tagName==='h1')),/WebShelf/);
});
test('legacy uppercase TV URLs redirect only to their lowercase counterpart',()=>{
  for(const cat of catalog.filter(c=>c.key.startsWith('tv-'))){
    const rule=config.redirects.find(r=>r.has?.some(h=>h.value===cat.key.replace('tv-','TV-')));
    assert.equal(rule.destination,'/category.html?type='+cat.key);
    assert.equal(rule.permanent,true);
  }
});
test('every generated byte is reproducible including home, category pages and configuration',()=>{
  for(const [file,expected] of Object.entries(require('../build.cjs').outputs())) assert.equal(read(file),expected,file);
});
